name: My First GitHub Action

on:
  push:
    branches:
      - main
      - ai

jobs:
  first-job:

    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello Sandeep! GitHub Actions is working."

      - name: Install dependencies
        run: npm ci

      - name: Show current date
        run: date

      - name: Show Node version
        run: node --version

      